[package]
name = "omniscope-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
omniscope-core = { workspace = true }
anyhow = { workspace = true }
